### ISSUE TITLE
问题: 关于一些没有看懂的东西

### ISSUE THREAD

**Issue by Akimotorakiyu** [pengtikui/WeUI-Simple-Guide#1]
## 样式 weui-media-box

`weui-media-box` 和
`weui-media-box_appmsg`的使用不是很理解,和单独的image比有什么区别?

## `weui-***_access`和`weui-***_link`

`weui-***_access`表示什么意思?
`weui-***_access`和`weui-***_link`区别意义?

## panel和cell的搭配

`panel`里面直接套`weui-media-box`可以生成列表,

`panel`里面列表可以用`weui-cells`吗

这些的区别是什么???

**Comment by pengtikui** [comment]
`weui-media-box` 属于一个容器，内部除了 `img` 外，还可以使用 `weui-media-box__title`、`weui-media-box__desc` 等内容，具体参考源码：[weui-media-box.less](https://github.com/Tencent/weui/blob/master/src/style/widget/weui-media-box/weui-media-box.less)

`weui-cell_access` 是 `cells` 内的一项，一般为 `a` 标签，表示一个链接，还附带右侧的箭头图标，颜色继承自父级；`weui-cell_link` 仅表示一个链接，有自己的颜色，具体参考源码：[weui-access.less](https://github.com/Tencent/weui/blob/master/src/style/widget/weui-cell/weui-access.less)

`panel` 和 `cells` 我认为他们是属于同一级别的，只是用处不同而已，`cells` 一般为简单的列表或表单；`panel` 一般是内容较复杂的列表，并且 `panel` 有 `hd` 和 `ft`，而 `cells` 没有

> 综上，不明白的地方看看源码就会懂了 😝
